import { getRecipeCatalog } from '../lib/catalog'
import { Grid } from '@mui/material';
import { useState } from 'react';
import { CacheProvider } from '@emotion/react';
import Catalog from '../components/catalog/catalog';
import Navbar from '../components/navbar/navbar';
import SearchBox from '../components/searchbox/searchbox';
import Head from 'next/head'
import createCache from '@emotion/cache';
import nookies from 'nookies'
import styles from '../styles/catalog.module.css'

const cache = createCache({
  key: 'css',
  prepend: true,
});

export async function getServerSideProps(ctx) {
  const cookies = nookies.get(ctx)
  const recipeCatalog = await getRecipeCatalog(cookies);
  return {
    props: {
      recipeCatalog,
    }
  };
}

export default function CatalogPage({ recipeCatalog }) {
  const [searchField, setSearchField] = useState('')
  const filteredRecipes = recipeCatalog.list.filter(entry => {
    return entry.name.toLowerCase().includes(searchField)
  })

  return (
    <CacheProvider value={cache}>
      <Head>
        <title>Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <Navbar/>
      <SearchBox setSearchField={setSearchField} />
      <Grid container className={styles.catalog}>
        <Catalog recipeCatalog={filteredRecipes}/>
      </Grid>
    </CacheProvider>
  )
}
