import { getRecipeCatalog } from '../lib/catalog'
import Catalog from '../components/catalog/catalog';
import styles from '../styles/catalog.module.css'
import { Grid } from '@mui/material';
import { useState } from 'react';
import Navbar from '../components/navbar/navbar';
import SearchBox from '../components/searchbox/searchbox';
import Head from 'next/head'

export async function getStaticProps() {
  const recipeCatalog = await getRecipeCatalog();
  return {
    props: {
      recipeCatalog,
    },
    revalidate: 60,
  };
}

export default function CatalogPage({ recipeCatalog }) {
  const [searchField, setSearchField] = useState('')
  const filteredRecipes = recipeCatalog.list.filter(entry => {
    return entry.name.toLowerCase().includes(searchField)
  })
  return (
    <>
    <Head>
      <title>Catalog</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta name="viewport" content="initial-scale=1, width=device-width" />
    </Head>
    <Navbar/>
    <SearchBox setSearchField={setSearchField} />
    <Grid container className={styles.catalog}>
      <Catalog recipeCatalog={filteredRecipes}/>
    </Grid>
    </>
  )
}
